version: "3.8"

services:
  payment.gateway:
    container_name: payment.gateway
    build:
      context: .
      dockerfile: src/PaymentGateway.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=7092
      - ASPNETCORE_URLS=https://+:7092;http://*:5067
      - AcquirerBank__BaseUrl=http://bank_simulator:8080/payments
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
    ports:
      - 5067:5067
      - 7092:7092
    depends_on:
      - bank_simulator


  bank_simulator:
    container_name: bank_simulator
    image: bbyars/mountebank:2.8.1
    ports:
      - "2525:2525"
      - "8080:8080"
    command: --configfile /imposters/bank_simulator.ejs
    volumes:
      - type: bind
        source: ./imposters
        target: /imposters
      